name: CI Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: >
          mvn --no-transfer-progress
          org.jacoco:jacoco-maven-plugin:prepare-agent
          verify
          org.jacoco:jacoco-maven-plugin:report
      - uses: actions/cache@v4
        with:
          path: ./target
          key: build-artifacts-cache
  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ./target
          key: build-artifacts-cache
      - name: SonarQube Analysis
        run: >
          mvn --no-transfer-progress
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --no-transfer-progress
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.qualitygate.wait=true