name: CI Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "camunda-bpm-nexus-ee",
              "username": "${{ secrets.CAMUNDA_REPO_USERNAME }}",
              "password": "${{ secrets.CAMUNDA_REPO_PASSWORD }}"
            },
            {
              "id": "ZK EE",
              "username": "${{ secrets.ZKOSS_REPO_USERNAME }}",
              "password": "${{ secrets.ZKOSS_REPO_PASSWORD }}"
            }]
      - name: Build
        run: >
          mvn --no-transfer-progress
          org.jacoco:jacoco-maven-plugin:prepare-agent
          verify
          org.jacoco:jacoco-maven-plugin:report
      - name: SonarQube Analysis
        run: >
          mvn --no-transfer-progress
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.links.scm=${{ github.server_url }}/${{ github.repository }}
          -Dsonar.qualitygate.wait=true