name: Security Check

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: >
          mvn --no-transfer-progress
          verify
          -DskipTests
      - uses: actions/cache@v4
        with:
          path: ./target
          key: build-artifacts-cache
  owasp-dependency-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ./target
          key: build-artifacts-cache
      - name: OWASP Dependency Check
        run: >
          mvn --no-transfer-progress
          org.owasp:dependency-check-maven:check
          -DfailBuildOnCVSS=0
          -DhostedSuppressionsUrl=https://raw.githubusercontent.com/daniel-kraemer/.github/main/owasp-suppressions.xml
          -DnvdDatafeedUrl=https://dependency-check.github.io/DependencyCheck_Builder/nvd_cache/nvdcve-{0}.json.gz
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: ./target/dependency-check-report.html
  license-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ./target
          key: build-artifacts-cache
      - name: Licence Check
        run: >
          mvn --no-transfer-progress
          org.codehaus.mojo:license-maven-plugin:third-party-report
      - name: Upload License Check Report
        uses: actions/upload-artifact@v4
        with:
          name: license-check-report
          path: ./target/site/*
  create-jira-issue:
    runs-on: ubuntu-latest
    needs: owasp-dependency-check
    if: failure()
    steps:
      - name: Create Jira Issue
        run: |
          issue_summary="$GITHUB_REPOSITORY @ $GITHUB_REF - Security Check failed"
          jql_query='project = "SEC" AND summary = "${issue_summary}" AND resolution != "DONE"'
          echo "${jql_query}"
#          RESPONSE=$(curl -X GET -H "Content-Type: application/json" -u "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }}" "${{ secrets.JIRA_API_ENDPOINT }}/rest/api/3/search?jql=${JQL_QUERY}")

          # Check if the issue exists
#          if [ "$(echo "$RESPONSE" | jq '.total')" -gt 0 ]; then
          data='{
            "fields": {
              "project": {
                "key": "SEC"
              },
              "summary": "${{ ISSUE_SUMMARY }}",
              "description": "Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\nBuild Artifacts: ${{ steps.artifact.outputs.url }}",
              "issuetype": {
                "name": "Bug"
              }
            }
          }'
          echo "${data}"
#          curl -X POST -H "Content-Type: application/json" -u "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }}" --data "${DATA}" "${{ secrets.JIRA_HOST }}/rest/api/3/issue"
#          fi