name: Security Check

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "camunda-bpm-nexus-ee",
              "username": "${{ secrets.CAMUNDA_REPO_USERNAME }}",
              "password": "${{ secrets.CAMUNDA_REPO_PASSWORD }}"
            },
            {
              "id": "ZK EE",
              "username": "${{ secrets.ZKOSS_REPO_USERNAME }}",
              "password": "${{ secrets.ZKOSS_REPO_PASSWORD }}"
            }]
      - name: Build
        run: >
          mvn --no-transfer-progress
          verify
          -DskipTests
      - name: OWASP Dependency Check
        if: success() || failure()
        run: >
          mvn --no-transfer-progress
          org.owasp:dependency-check-maven:check
          -Dformats=HTML,JSON
          -DfailBuildOnCVSS=0
          -DhostedSuppressionsUrl=https://raw.githubusercontent.com/daniel-kraemer/.github/main/owasp-suppressions.xml
          -DnvdDatafeedUrl=https://dependency-check.github.io/DependencyCheck_Builder/nvd_cache/nvdcve-{0}.json.gz
      - name: Create Jira Issues for CVE
        if: success() || failure()
        run: |
          curl -sOL https://raw.githubusercontent.com/daniel-kraemer/.github/main/create_jira_issue.sh
          chmod +x create_jira_issue.sh
          ./create_jira_issue.sh ./target/dependency-check-report.json ${{ secrets.JIRA_API_URL }} ${{ secrets.JIRA_API_USER }} ${{ secrets.JIRA_API_TOKEN }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: owasp-dependency-check-report
          path: ./target/dependency-check-report.html
      - name: Licence Check
        if: success() || failure()
        run: >
          mvn --no-transfer-progress
          org.codehaus.mojo:license-maven-plugin:third-party-report
          org.codehaus.mojo:license-maven-plugin:add-third-party
          -Dlicense.failOnMissing=true
          -Dlicense.failOnBlacklist=true
          -Dlicense.includedLicenses=https://raw.githubusercontent.com/daniel-kraemer/.github/main/included-licenses.txt
          -Dlicense.excludedLicenses=https://raw.githubusercontent.com/daniel-kraemer/.github/main/excluded-licenses.txt
      - name: Upload License Check Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: license-check-report
          path: ./target/site/*