name: Security Check

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/ci.yml
      - name: OWASP Dependency Check
        if: success() || failure()
        run: >
          mvn --no-transfer-progress
          org.owasp:dependency-check-maven:check
          -Dformats=HTML,JSON
          -DfailBuildOnCVSS=0
          -DhostedSuppressionsUrl=https://raw.githubusercontent.com/daniel-kraemer/.github/main/owasp-suppressions.xml
          -DnvdDatafeedUrl=https://dependency-check.github.io/DependencyCheck_Builder/nvd_cache/nvdcve-{0}.json.gz
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: owasp-dependency-check-report
          path: ./target/dependency-check-report.html
      - name: Licence Check
        if: success() || failure()
        run: >
          mvn --no-transfer-progress
          org.codehaus.mojo:license-maven-plugin:third-party-report
          org.codehaus.mojo:license-maven-plugin:add-third-party
          -Dlicense.failOnMissing=true
          -Dlicense.failOnBlacklist=true
          -Dlicense.includedLicenses=https://raw.githubusercontent.com/daniel-kraemer/.github/main/included-licenses.txt
          -Dlicense.excludedLicenses=https://raw.githubusercontent.com/daniel-kraemer/.github/main/excluded-licenses.txt
      - name: Upload License Check Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: license-check-report
          path: ./target/site/*